name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  perxenic-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: perxenic-metrics.svg
          token: ${{ secrets.METRICS_TOKEN_AUSEAWESOME }}
          base: classic
          user: perxenic-studios
  perxenic-lines:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: perxenic-lines.svg
          token: ${{ secrets.METRICS_TOKEN_AUSEAWESOME }}
          base: ""
          plugin_lines: yes
          user: perxenic-studios
  auseawesome-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: auseawesome-metrics.svg
          token: ${{ secrets.METRICS_TOKEN_AUSEAWESOME }}
          base: classic
          plugin_isocalendar: yes
    auseawesome-isocalendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: auseawesome-isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN_AUSEAWESOME }}
          base: ""
          plugin_isocalendar: yes
